dist: bionic

sudo: required

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- -j2
  - cd Libraries
  - ./ActivationFunctionsTest
  - ./ExclusiveOrNeuralNetworkTest
  - ./NeuralNetworkBaseTest
