#ifndef NEURALNETWORK_SIMPLE_NEURAL_NETWORK_H
#define NEURALNETWORK_SIMPLE_NEURAL_NETWORK_H

class FeedForwardNetwork
{
public:
  void PrintHello();
};

#endif // NEURALNETWORK_SIMPLE_NEURAL_NETWORK_H
